.default_schedule_rules: &schedule_rules
  - if: '$CI_PIPELINE_SOURCE == "schedule"'
  - when: never

stages:
  - deploy_infra

deploy_infra:
  stage: deploy_infra
  image: python:3.11-slim
  tags:
    - ansible
    - automation
  before_script:
    - chmod -R o-w .
    - apt-get update -qq
    - apt-get install -y --no-install-recommends sshpass git openssh-client
    - pip install --no-cache-dir ansible
    - echo "[INFO] Creating Ansible credentials file"
    - |
      cat <<EOF > ./inventory/group_vars/cluster/credentials.yml
      ansible_user: "${ANSIBLE_USER}"
      ansible_password: "${ANSIBLE_PASSWORD}"
      EOF
  script:
    - echo "[INFO] Starting Ansible playbook"
    - ansible-playbook -i inventory/hosts.ini playbooks/setup_servers.yml
  rules:
    *schedule_rules