---

ansible_host: "{{ lan_prefix }}.1.97"
target_host: server2

lxc_container:
  name: nginx-web
  id: 104
  template: "debian-13-standard_*_amd64.tar.zst"
  memory: 1024
  swap: 512
  cores: 2
  rootfs: "local-lvm:8"
  net_bridge: "vmbr0"
  net_ip_address: "{{ ansible_host }}"
  net_subnet: 24
  net_gateway: "{{ net_gateway }}"
  lxc_unprivileged: true
  start: true
  features:
    - nesting=1
    - keyctl=1
  root_password: "{{ ansible_password }}"
  users:
    - name: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      sudo: true

github_repositories:
  - repo: "Naretto95/Otteran"
    dest: "/opt/otteran"
    version: "main"

  - repo: "Naretto95/Resume"
    dest: "/opt/resume"
    version: "master"

static_sites:
  - name: otteran
    domain: "{{ domain }}"
    root: "/opt/otteran"

  - name: resume
    domain: "cv.{{ domain }}"
    root: "/opt/resume"