---

- name: Gather cluster status
  command: pvecm status
  register: cluster_status
  ignore_errors: true
  changed_when: false

- name: Include master tasks
  include_tasks: master.yml
  when: cluster_master | default(false) | bool

- name: Include node tasks
  include_tasks: node.yml
  when: not (cluster_master | default(false) | bool)