---

- name: Get project info
  uri:
    url: "http://{{ gitlab_container.hostname }}/api/v4/projects?search={{ project_name }}"
    method: GET
    headers:
      PRIVATE-TOKEN: "{{ gitlab_token }}"
  changed_when: false
  register: project_info

- name: Create GitLab project if not found
  uri:
    url: "http://{{ gitlab_container.hostname }}/api/v4/projects"
    method: POST
    headers:
      PRIVATE-TOKEN: "{{ gitlab_token }}"
    body_format: json
    body:
      name: "{{ project_name }}"
      visibility: "private"
    status_code: 201
  when: project_info.json | length == 0
  register: project_create

- name: Set git_repo fact
  set_fact:
    git_repo: "{{ project_create.json if project_info.json|length == 0 else project_info.json[0] }}"

- name: Set Git repository URL facts
  set_fact:
    git_repo_url: "{{ git_repo.http_url_to_repo | regex_replace('http://', 'http://root:' + gitlab_token + '@') | regex_replace('gitlab.local', gitlab_container.hostname) }}"
    git_repo_ssh: "ssh://git@{{ gitlab_container.hostname }}:2222/{{ git_repo.path_with_namespace }}.git"

- name: Generate SSH key for GitLab
  openssh_keypair:
    path: "~/.ssh/gitlab_deploy_key"
    type: rsa
    size: 4096
    state: present
  register: ssh_key

- name: Add deploy key to GitLab project
  uri:
    url: "http://{{ gitlab_container.hostname }}/api/v4/projects/{{ git_repo.id }}/deploy_keys"
    method: POST
    headers:
      PRIVATE-TOKEN: "{{ gitlab_token }}"
    body_format: json
    body:
      title: "Ansible deploy key"
      key: "{{ ssh_key.public_key }}"
      can_push: true
    status_code: 201

- name: Deploy mirror script
  ansible.builtin.template:
    src: github_gitlab_mirror.sh.j2
    dest: "{{ base_directory }}/github_gitlab_mirror.sh"
    mode: '0755'

- name: Create systemd service file
  ansible.builtin.copy:
    dest: /etc/systemd/system/github_gitlab_mirror.service
    content: |
      [Unit]
      Description=GitHub → GitLab mirror job
      After=network-online.target

      [Service]
      Type=oneshot
      ExecStart={{ base_directory }}/github_gitlab_mirror.sh
      TimeoutStartSec=300

      [Install]
      WantedBy=multi-user.target
  notify: Reload systemd

- name: Create systemd timer file
  ansible.builtin.copy:
    dest: /etc/systemd/system/github_gitlab_mirror.timer
    content: |
      [Unit]
      Description=Run GitHub → GitLab mirror every minute

      [Timer]
      OnBootSec=30s
      OnUnitActiveSec=60s
      Unit=github_gitlab_mirror.service

      [Install]
      WantedBy=timers.target
  notify: Reload systemd

- name: Enable and start mirror timer
  ansible.builtin.systemd:
    name: github_gitlab_mirror.timer
    enabled: true
    state: started

- name: Initiate first github push
  ansible.builtin.command: "{{ base_directory }}/github_gitlab_mirror.sh"
  changed_when: false