---

- name: Set Git repository registry fact
  set_fact:
    git_repo_registry: "{{ gitlab_container.hostname }}:5050/{{ git_repo.path_with_namespace }}"

- name: Log in to GitLab container registry using token
  community.docker.docker_login:
    registry_url: "{{ gitlab_container.hostname }}:5050"
    username: "oauth2"
    password: "{{ gitlab_token }}"

- name: Push Docker images to GitLab
  block:
    - name: Load Docker image from tarball
      community.docker.docker_image:
        load_path: "{{ base_directory }}/{{ item.name }}/{{ item.name }}_{{ item.tag }}.tar"
        source: load

    - name: Remove old Docker image from registry (if exists)
      community.docker.docker_image:
        name: "{{ git_repo_registry }}/{{ item.name }}"
        tag: "{{ item.tag }}"
        state: absent

    - name: Push Docker image to GitLab registry
      community.docker.docker_image:
        name: "{{ git_repo_registry }}/{{ item.name }}"
        tag: "{{ item.tag }}"
        push: true
        source: local

    - name: Remove local Docker image after pushing
      community.docker.docker_image:
        name: "{{ item.name }}"
        tag: "{{ item.tag }}"
        state: absent

  loop: "{{ docker_images }}"
  loop_control:
    loop_var: item

- name: Logout from GitLab registry
  community.docker.docker_login:
    registry_url: "{{ gitlab_container.hostname }}:5050"
    state: absent