---

- name: Set Git repository registry fact
  set_fact:
    git_repo_registry: "{{ gitlab_container.hostname }}:5050/{{ git_repo.path_with_namespace }}"

- name: Log in to GitLab container registry using token
  community.docker.docker_login:
    registry_url: "{{ gitlab_container.hostname }}:5050"
    username: "oauth2"
    password: "{{ gitlab_token }}"

- name: Load Docker images from tarball
  community.docker.docker_image:
    load_path: "{{ base_directory }}/{{ image.name }}/{{ image.name }}_{{ image.tag }}.tar"
    source: load
  loop: "{{ docker_images }}"
  loop_control:
    loop_var: image

- name: Remove old Docker images (if exists)
  community.docker.docker_image:
    name: "{{ git_repo_registry }}/{{ image.name }}"
    tag: "{{ image.tag }}"
    state: absent
  loop: "{{ docker_images }}"
  loop_control:
    loop_var: image

- name: Push Docker images to GitLab registry
  community.docker.docker_image:
    name: "{{ git_repo_registry }}/{{ image.name }}"
    tag: "{{ image.tag }}"
    push: true
    source: local
  loop: "{{ docker_images }}"
  loop_control:
    loop_var: image

- name: Remove local Docker images after saving to tarball
  community.docker.docker_image:
    name: "{{ image.name }}"
    tag: "{{ image.tag }}"
    state: absent
  loop: "{{ docker_images }}"
  loop_control:
    loop_var: image

- name: Logout from GitLab registry
  community.docker.docker_login:
    registry_url: "{{ gitlab_container.hostname }}:5050"
    state: absent