---

- name: Wait for GitLab container to be healthy
  community.docker.docker_container_info:
    name: "{{ gitlab_container.name }}"
  register: gitlab_info
  retries: 30
  delay: 10
  until: gitlab_info.container.State.Health.Status == "healthy"

- name: Wait for GitLab web service
  uri:
    url: "http://{{ gitlab_container.hostname }}/users/sign_in"
    method: GET
    status_code: 200
  register: gitlab_ui
  retries: 30
  delay: 10
  until: gitlab_ui.status == 200
  changed_when: false