---

- name: Install required packages for Docker (Debian/Ubuntu)
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Add Docker GPG key (Debian/Ubuntu)
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Add Docker repository (Debian/Ubuntu)
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }} {{ ansible_facts['distribution_release'] }} stable"
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install Docker Engine (Debian/Ubuntu)
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install required packages for Docker (RHEL/CentOS)
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Add Docker repository (RHEL/CentOS)
  yum_repository:
    name: docker
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Docker Engine (RHEL/CentOS)
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true