---

- name: Gather services definitions from services
  set_fact:
    lxc_containers: "{{ services | select('in', groups['lxc_containers']) | map('extract', hostvars, 'lxc_container') | select('defined') | list }}"
    virtual_machines: "{{ services | select('in', groups['virtual_machines']) | map('extract', hostvars, 'virtual_machine') | select('defined') | list }}"

- name: Stop role if no lxc_containers or virtual_machines
  meta: end_role
  when: lxc_containers | length == 0 and virtual_machines | length == 0

- name: Get existing Proxmox VMs
  ansible.builtin.command: qm list
  register: qm_list
  changed_when: false

- name: Get existing Proxmox LXCs
  ansible.builtin.command: pct list
  register: pct_list
  changed_when: false

- name: Parse existing VM/LXC IDs
  set_fact:
    existing_vms: "{{ qm_list.stdout_lines[1:] | map('split') | map('first') | map('int') | list }}"
    existing_lxcs: "{{ pct_list.stdout_lines[1:] | map('split') | map('first') | map('int') | list }}"

- name: Filter services that do not exist yet
  set_fact:
    virtual_machines: "{{ virtual_machines | rejectattr('id', 'in', existing_vms) | list }}"
    lxc_containers: "{{ lxc_containers | rejectattr('id', 'in', existing_lxcs) | list }}"

- name: Remove VMs on proxmox server
  include_role: remove_proxmox_instance
  when: services_state == 'absent'

- block:

    - name: Ensure LXC template is present
      ansible.builtin.command: "pveam download local {{ item.template | regex_replace('^local:vztmpl/', '') }}"
      args:
        creates: "/var/lib/vz/template/cache/{{ item.template | regex_replace('^local:vztmpl/', '') }}"
      changed_when: false
      loop: "{{ lxc_containers }}"

    - name: Check if VM image exists
      ansible.builtin.stat:
        path: "/var/lib/vz/template/cache/{{ item.image | basename }}"
      register: vm_image_stat
      loop: "{{ virtual_machines }}"

    - name: Download VM image
      ansible.builtin.get_url:
        url: "{{ item.item.image }}"
        dest: "/var/lib/vz/template/cache/{{ item.item.image | basename }}"
        mode: "0644"
        timeout: 600
      when: not item.stat.exists
      loop: "{{ vm_image_stat.results }}"

    - name: Create VMs on proxmox server
      include_tasks: install_instances.yml

  when: services_state == 'present'