---

- name: Add APT repositories (deb822)
  ansible.builtin.deb822_repository:
    name: "{{ repo.filename }}"
    types: "{{ repo.types }}"
    uris: "{{ repo.uris }}"
    suites: "{{ repo.suites }}"
    enabled: true
    components: "{{ repo.components }}"
    signed_by: "/usr/share/keyrings/{{ repo.filename }}.gpg"
    state: "{{ repos_state }}"
