---

- name: Add APT repositories (Deb822 format)
  ansible.builtin.deb822_repository:
    name: "{{ item.filename }}"
    types: ["deb"]
    uris: "{{ item.repo.split(' ')[1] }}"
    suites: "{{ item.repo.split(' ')[2] }}"
    components: "{{ item.repo.split(' ')[3:] }}"
    enabled: true
    signed_by: "/usr/share/keyrings/{{ item.filename }}.gpg"
    state: present
  loop: "{{ debian_repos }}"

- name: Remove Proxmox enterprise .sources file
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/{{ item }}"
    state: absent
  loop:
    - pve-enterprise.sources
    - ceph.sources
