---

- name: Check if GPU device exists
  stat:
    path: "/sys/bus/pci/devices/{{ gpu_device_id }}"
  register: gpu_device
  when: unmount_gpu

- name: Unmount GPU from PCI bus
  shell: "echo 1 > /sys/bus/pci/devices/{{ gpu_device_id }}/remove"
  when: 
    - unmount_gpu 
    - gpu_device.stat.exists
  changed_when: false

- name: Remount (rescan) PCI bus
  shell: "echo 1 > /sys/bus/pci/rescan"
  when: not unmount_gpu
  changed_when: false