---

- name: Fail if host is not part of the "cluster" group
  ansible.builtin.fail:
    msg: "This role can only be run on hosts in the 'cluster' group!"
  when: "'cluster' not in group_names"

- name: Fail if host OS is not Proxmox
  ansible.builtin.fail:
    msg: "This role can only be run on Proxmox hosts!"
  when: host_os != "proxmox"

- name: Unmount GPU from PCI bus
  shell: "echo 1 > /sys/bus/pci/devices/{{ gpu_device_id }}/remove"
  when: unmount_gpu
  changed_when: false

- name: Remount (rescan) PCI bus
  shell: "echo 1 > /sys/bus/pci/rescan"
  when: not unmount_gpu
  changed_when: false