- name: Ensure Docker networks exist
  community.docker.docker_network:
    name: "{{ item.key }}"
    driver: bridge
    state: present
  loop: "{{ docker_networks | dict2items }}"
  when: docker_networks is defined

- name: Create container folders in user's base directory with associated volumes
  include_tasks: create_container.yml
  loop: "{{ docker_services }}"
  loop_control:
    loop_var: container