---

- block:
    - name: Configure DNS servers
      copy:
        dest: /etc/resolv.conf
        content: |
          {% for ns in dns_servers %}
          nameserver {{ ns }}
          {% endfor %}
      when: os_family in ["Debian", "Proxmox"]

  rescue:
    - name: Fallback to raw method (no Python on host)
      raw: |
        if [ -f /etc/resolv.conf ]; then
          : > /etc/resolv.conf
        fi
        {% for ns in dns_servers %}
        echo "nameserver {{ ns }}" >> /etc/resolv.conf
        {% endfor %}
      when: os_family in ["Debian", "Proxmox"]
      changed_when: false

- name: Test DNS connectivity
  raw: ping -c 1 8.8.8.8
  register: ping_result
  ignore_errors: true
  changed_when: false

- name: Fail if DNS or network is not reachable
  fail:
    msg: "DNS or network not working on {{ inventory_hostname }}"
  when: ping_result.rc != 0