---

- name: Clear resolv.conf
  raw: "echo '' > /etc/resolv.conf"
  when: os_family == "Proxmox"
  changed_when: false

- name: Configure DNS servers using raw
  raw: |
    {% for ns in dns_servers %}
    echo "nameserver {{ ns }}" >> /etc/resolv.conf
    {% endfor %}
  when: os_family == "Proxmox"
  changed_when: false

- name: Configure DNS servers
  copy:
    dest: /etc/resolv.conf
    content: |
      {% for ns in dns_servers %}
      nameserver {{ ns }}
      {% endfor %}
  when: os_family == "Debian"

- name: Test DNS connectivity
  raw: ping -c 1 8.8.8.8
  register: ping_result
  ignore_errors: true
  changed_when: false

- name: Fail if DNS or network is not reachable
  fail:
    msg: "DNS or network not working on {{ inventory_hostname }}"
  when: ping_result.rc != 0