---

- block:

    - name: Create user if not exists
      ansible.builtin.command: >
        pct exec {{ lxc_container.id }} -- bash -c "id -u {{ container_user.name }} || adduser --disabled-password --gecos '' {{ container_user.name }}"
      changed_when: false

    - name: Set user password
      ansible.builtin.command: >
        pct exec {{ lxc_container.id }} -- bash -c "echo '{{ container_user.name }}:{{ container_user.password }}' | chpasswd"
      changed_when: false

    - name: Ensure sudo is installed in container
      ansible.builtin.command: >
        pct exec {{ lxc_container.id }} -- bash -c "dpkg -s sudo >/dev/null 2>&1 || (apt-get update -y && apt-get install -y sudo)"
      changed_when: false

    - name: Add user to sudo group if needed
      ansible.builtin.command: >
        pct exec {{ lxc_container.id}} -- usermod -aG sudo {{ container_user.name }}
      changed_when: false
      when: container_user.sudo | default(false)

  delegate_to: "{{ target_host}}"