---

- name: Gather users definitions from host
  set_fact:
    lxc_containers_users: "{{ (lxc_container | default({})).users }}"
    virtual_machines_users: "{{ (virtual_machine | default({})).users }}"

- name: Stop role if no users in lxc_containers or virtual_machines
  meta: end_role
  when: lxc_containers_users | length == 0 and virtual_machines_users | length == 0

- name: Create users for all containers
  include_tasks: create_users_container.yml
  loop: "{{ lxc_containers_users }}"
  loop_control:
    loop_var: container_user

- name: Create users for all virtual machines
  include_tasks: create_users_virtual_machine.yml
  loop: "{{ virtual_machines_users }}"
  loop_control:
    loop_var: virtual_machine_user