---

ansible_host: 192.168.1.95
target_host: server2

lxc_container:
  name: django-app
  id: 101
  template: "debian-13-standard_*_amd64.tar.zst"
  memory: 2048
  swap: 512
  cores: 2
  rootfs: "local-lvm:10"
  net_bridge: "vmbr0"
  net_ip_address: "{{ ansible_host }}"
  net_subnet: 24
  net_gateway: "{{ net_gateway }}"
  lxc_unprivileged: false
  start: true
  features:
    - nesting=1
    - keyctl=1
  root_password: "{{ ansible_password }}"
  users:
    - name: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      sudo: true

django_systemd_schedulers:
  - name: "ottervault-cve-cpe-scheduler"
    description: "Update Ottervault CPE/CVE Service"
    exec_start: "{{ venv_dir }}/bin/python manage.py update_db"
    user: "root"
    group: "root"
    timer:
      description: "Update Ottervault CPE/CVE Timer"
      on_calendar: "04:00"
      persistent: true

github_repositories:
  - repo: "Naretto95/{{ django_app_name }}"
    dest: "/opt/{{ django_app_name }}"
    version: "main"
    token: "{{ github_token }}"