---

ansible_host: 192.168.1.95
target_host: server2

lxc_container:
  name: django-app
  id: 101
  template: "local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst"
  memory: 2048
  swap: 512
  cores: 2
  rootfs: "local-lvm:10"
  net_bridge: "vmbr0"
  net_ip_address: "{{ ansible_host }}"
  net_subnet: 24
  net_gateway: "{{ net_gateway }}"
  lxc_unprivileged: true
  start: true
  features:
    - nesting=1
    - keyctl=1
  root_password: "{{ ansible_password }}"
  users:
    - name: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      sudo: true