---

- name: Gather services definitions from services
  set_fact:
    lxc_containers: "{{ services | select('in', groups['lxc_containers']) | map('extract', hostvars, 'lxc_container') | select('defined') | list }}"
    virtual_machines: "{{ services | select('in', groups['virtual_machines']) | map('extract', hostvars, 'virtual_machine') | select('defined') | list }}"

- name: Delete LXC containers on Proxmox
  community.proxmox.proxmox:
    api_user: "{{ ansible_user }}@pam"
    api_password: "{{ ansible_password }}"
    api_host: "{{ ansible_host }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ item.id }}"
    state: absent
  loop: "{{ lxc_containers }}"

- name: Delete VMs on Proxmox
  community.proxmox.proxmox:
    api_user: "{{ ansible_user }}@pam"
    api_password: "{{ ansible_password }}"
    api_host: "{{ ansible_host }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ item.id }}"
    state: absent
  loop: "{{ virtual_machines }}"