---

- name: Read runtime.txt
  ansible.builtin.slurp:
    src: "{{ django_app_dir }}/runtime.txt"
  register: runtime_file
  ignore_errors: true
  failed_when: false

- block:

    - name: Set raw python version from runtime.txt
      ansible.builtin.set_fact:
        python_runtime: >-
          {{ (runtime_file.content | b64decode).strip() }}

    - name: Normalize python version (major.minor only)
      ansible.builtin.set_fact:
        python_version: >-
          {{
            (python_runtime.split('-')[1] if 'python-' in python_runtime else python_runtime)
            .rsplit('.', 1)[0]
          }}

  when: runtime_file is defined and runtime_file.content is defined

- name: Install python {{ python_version }} with pyenv
  ansible.builtin.command:
    cmd: "pyenv install -s {{ python_version }}"
  changed_when: false
  
- name: Catch python binary
  ansible.builtin.shell:
    cmd: |
      eval "$(pyenv init -)"
      echo $(pyenv shell {{ python_version }}; pyenv which python)
  register: python_binary
  changed_when: false

- name: Create virtualenv
  ansible.builtin.command:
    cmd: "{{ python_binary.stdout }} -m venv {{ venv_dir }}"
    creates: "{{ venv_dir }}/bin/python"

- name: Install Python dependencies
  ansible.builtin.pip:
    requirements: "{{ django_app_dir }}/requirements.txt"
    virtualenv: "{{ venv_dir }}"

- name: Create .env file
  ansible.builtin.template:
    src: env.j2
    dest: "{{ django_app_dir }}/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"

- name: Install systemd service
  ansible.builtin.template:
    src: gunicorn.service.j2
    dest: "/etc/systemd/system/{{ django_app_name }}.service"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start service
  ansible.builtin.systemd:
    name: "{{ django_app_name }}"
    enabled: true
    state: restarted

- name: Create nginx site config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ django_app_name }}"
    owner: root
    group: root
    mode: "0644"

- name: Enable nginx site
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ django_app_name }}"
    dest: "/etc/nginx/sites-enabled/{{ django_app_name }}"
    state: link

- name: Remove default nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Ensure nginx is running
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: restarted