---

- name: Delete LXC container on Proxmox
  community.proxmox.proxmox:
    api_user: "{{ ansible_user }}"
    api_password: "{{ ansible_password }}"
    api_host: "{{ ansible_host }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ container.id }}"
    state: absent