---

- name: Find installed matching LXC template
  ansible.builtin.find:
    paths: /var/lib/vz/template/cache
    patterns: "{{ container.template }}"
    use_regex: false
    file_type: file
  register: templates

- block:

    - name: Select newest installed template
      ansible.builtin.set_fact:
        latest_template: >-
          {{
            templates.files
            | map(attribute='path')
            | map('basename')
            | sort
            | last
          }}

    - name: Create LXC container on Proxmox
      community.proxmox.proxmox:
        api_user: "{{ ansible_user }}@pam"
        api_password: "{{ ansible_password }}"
        api_host: "{{ ansible_host }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ container.id }}"
        hostname: "{{ container.name }}"
        ostemplate: "local:vztmpl/{{ latest_template }}"
        memory: "{{ container.memory }}"
        swap: "{{ container.swap }}"
        cores: "{{ container.cores }}"
        unprivileged: "{{ container.lxc_unprivileged }}"
        features: "{{ container.features }}"
        password: "{{ container.root_password }}"
        netif:
          net0: "name=eth0,bridge={{ container.net_bridge }},ip={{ container.net_ip_address }}/{{ container.net_subnet }},gw={{ container.net_gateway }}"
        disk: "{{ container.rootfs }}"
        state: present

    - name: Start LXC container
      community.proxmox.proxmox:
        api_user: "{{ ansible_user }}@pam"
        api_password: "{{ ansible_password }}"
        api_host: "{{ ansible_host }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ container.id }}"
        state: started

    - include_tasks: wait_ssh_healthy.yml
      vars:
        ip_address: "{{ container.net_ip_address }}"

  delegate_to: localhost