---

- block:

    - name: Create VM on Proxmox
      community.proxmox.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: "{{ ansible_user }}@pam"
        api_password: "{{ ansible_password }}"
        clone: "{{ vm.template }}"
        newid: "{{ vm.id }}"
        name: "{{ vm.name }}"
        node: "{{ proxmox_node }}"
        state: present

    - name: Configure VM on Proxmox
      community.proxmox.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: "{{ ansible_user }}@pam"
        api_password: "{{ ansible_password }}"
        vmid: "{{ vm.id }}"
        node: "{{ proxmox_node }}"
        net:
          net0: "virtio,bridge={{ vm.net_bridge }}"
        ipconfig:
          ipconfig0: "ip={{ vm.net_ip_address }}/{{ vm.net_subnet }},gw={{ vm.net_gateway }}"
        ciuser: "{{ vm.cloud_user }}"
        cipassword: "{{ vm.cloud_password }}"
        update: true
        update_unsafe: true

    - name: Start VM
      community.proxmox.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: "{{ ansible_user }}@pam"
        api_password: "{{ ansible_password }}"
        vmid: "{{ vm.id }}"
        node: "{{ proxmox_node }}"
        state: started

  delegate_to: localhost