---

- block:

    - name: Ensure SSH keypair exists
      include_role:
        name: common/ssh_keypair

    - name: Create VM on Proxmox
      community.proxmox.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: "{{ ansible_user }}@pam"
        api_password: "{{ ansible_password }}"
        clone: "{{ vm.template }}"
        newid: "{{ vm.id }}"
        name: "{{ vm.name }}"
        node: "{{ proxmox_node }}"
        full: true
        state: present

    - name: Configure VM on Proxmox
      community.proxmox.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: "{{ ansible_user }}@pam"
        api_password: "{{ ansible_password }}"
        vmid: "{{ vm.id }}"
        node: "{{ proxmox_node }}"
        ciuser: "{{ vm.cloud_user }}"
        cipassword: "{{ vm.cloud_password }}"
        sshkeys: "{{ ssh_public_key }}"
        cores: "{{ vm.cores }}"
        scsi: "{{ vm.scsi }}"
        memory: "{{ vm.memory }}"
        net:
          net0: "virtio,bridge={{ vm.net_bridge }}"
        ipconfig:
          ipconfig0: "ip={{ vm.net_ip_address }}/{{ vm.net_subnet }},gw={{ vm.net_gateway }}"
        update: true
        update_unsafe: true

    - name: Start VM
      community.proxmox.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: "{{ ansible_user }}@pam"
        api_password: "{{ ansible_password }}"
        vmid: "{{ vm.id }}"
        node: "{{ proxmox_node }}"
        state: started

    - name: Wait for SSH to become available on VM
      ansible.builtin.wait_for:
        host: "{{ vm.net_ip_address }}"
        port: 22
        delay: 10
        timeout: 300

  delegate_to: localhost

- name: Create users on VM
  include_role:
    name: services/user_management

- name: Make sure SSH Key is removed from VM
  community.proxmox.proxmox_kvm:
    api_host: "{{ ansible_host }}"
    api_user: "{{ ansible_user }}@pam"
    api_password: "{{ ansible_password }}"
    vmid: "{{ vm.id }}"
    node: "{{ proxmox_node }}"
    sshkeys: ""
    update: true
    update_unsafe: true
  delegate_to: localhost