---

- name: Wait for cloud-init to finish
  community.general.cloud_init_data_facts:
  delegate_to: "{{ vm.net_ip_address }}"
  vars:
    ansible_user: "{{ vm.cloud_user }}"
    ansible_password: "{{ vm.cloud_password }}"
  register: cloudinit
  retries: 30
  delay: 5
  until: cloudinit.ansible_facts.cloud_init_status.status == "done"

- name: Wait for SSH to become available on VM
  ansible.builtin.wait_for:
    host: "{{ vm.net_ip_address }}"
    port: 22
    delay: 10
    timeout: 300