---

- name: Deploy proxmox containers
  hosts: cluster
  roles:
    - services/lxc_containers
    - services/terraform
    - services/user_management

- name: Bootstrap service nodes (DNS, repos, packages)
  hosts: services
  gather_facts: false
  roles:
    - common/os_detect
    - common/dns_setup
    - common/bootstrap
    - common/repositories
    - common/packages

- name: Deploy proxmox services specific configuration
  hosts: services
  roles:
    - role: services/install_wireguard
      when: inventory_hostname == 'wireguard'

    - role: services/postgresql
      when: inventory_hostname == 'django-db'