---

- name: Bootstrap django nodes (DNS, repos, packages)
  hosts: django
  gather_facts: false
  roles:
    - services/user_management
    - common/dns_setup
    - common/bootstrap
    - common/repositories
    - common/packages
    - services/github_repositories

- name: Deploy django services specific configuration
  hosts: django
  roles:

    - role: services/postgresql
      when: inventory_hostname == 'django-db'

    - role: services/django_app
      when: inventory_hostname == 'django-app'