---

- name: Deploy proxmox services
  hosts: cluster
  roles:
    - services/proxmox_templates
    - services/proxmox_instances
    - services/terraform

- name: Bootstrap service nodes (DNS, repos, packages)
  hosts: services
  gather_facts: false
  roles:
    - services/user_management
    - common/dns_setup
    - common/bootstrap
    - common/repositories
    - common/packages
    - services/github_repositories

- name: Deploy proxmox services specific configuration
  hosts: services
  roles:
    - role: services/install_wireguard
      when: inventory_hostname == 'wireguard'

    - role: services/postgresql
      when: inventory_hostname == 'django-db'